version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://distributedsystems6:ds1234@auth.tvhv5yi.mongodb.net/Authentication?retryWrites=true&w=majority&appName=Auth
      - JWT_SECRET=secret
      - EMAIL_USER=tdmahindarathne@gmail.com
      - EMAIL_PASS=cdbribzpyuaqqqsd
      - PORT=5000
      - GOOGLE_CLIENT_ID=703814824617-cinrnonku243qlmlmg453crqgtl94ovl.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    networks:
      - food-delivery-network

  restaurant-service:
    build: ./services/restaurant-service
    container_name: restaurant-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://udulajoker026:CvARzY4spvLIQ75l@cluster0.2imectr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=secret
      - EMAIL_USER=tdmahindarathne@gmail.com
      - EMAIL_PASS=cdbribzpyuaqqqsd
      - PORT=5001
      - GOOGLE_CLIENT_ID=703814824617-cinrnonku243qlmlmg453crqgtl94ovl.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    networks:
      - food-delivery-network

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb+srv://udulajoker026:CvARzY4spvLIQ75l@cluster0.2imectr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5002
      - JWT_SECRET=secret
      - STRIPE_SECRET_KEY=sk_test_51RFXHwRrlMKGq9bMZnBHYawb33nMVND8wcPO7tbr22sIignw7YySyD42Ui8EqGPN9R41Zz6nNPZ4Qp4Vv8XWYZRY00teZMHq0h
      - STRIPE_WEBHOOK_SECRET=whsec_haPAOmcjdrIPE2FLZSTleoYAlzJD4D2M
      - EMAIL_USER=madhini00@gmail.com
      - EMAIL_PASS=qpso aweo pmlk xyow
    networks:
      - food-delivery-network

  delivery-service:
    build:
      context: ./services/delivery-service
      dockerfile: Dockerfile
    container_name: delivery-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb+srv://udulajoker026:CvARzY4spvLIQ75l@cluster0.2imectr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=secret
      - EMAIL_USER=tdmahindarathne@gmail.com
      - EMAIL_PASS=cdbribzpyuaqqqsd
      - PORT=5003
      - GOOGLE_CLIENT_ID=703814824617-cinrnonku243qlmlmg453crqgtl94ovl.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - ORDER_SERVICE_URL=http://order-service:5002/api/orders
    depends_on:
      - order-service
    networks:
      - food-delivery-network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb+srv://distributedsystems6:ds1234@auth.tvhv5yi.mongodb.net/Notifications?retryWrites=true&w=majority&appName=Auth
      - EMAIL_USER=distributedsystems6@gmail.com
      - EMAIL_PASS=xsxdjfclfmdsazez
      - TEXTBELT_KEY=textbelt
      - TWILIO_ACCOUNT_SID=ACe4ef357dacfcb812f7a8e9c339dd9ef2
      - TWILIO_AUTH_TOKEN=e332e0f6035b9fa6fea5d97d79d10c41
      - TWILIO_PHONE_NUMBER=+14014098175
      - PORT=5004
    networks:
      - food-delivery-network

  frontend:
    build: ../food-delivery-system-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51RFXHwRrlMKGq9bMbT1dBLXnGGkqMguFHeaqOdgM6zaEkUGEkyQSn0J72DtSnSHEPOJ7EqyQbNILaVpmFGNTSY6v008YHy958A
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyCmoMpEzjYLj2TH148EMIdzaHg0QzUj7ko
    depends_on:
      - auth-service
      - restaurant-service
      - order-service
      - delivery-service
      - notification-service
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge
