apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://distributedsystems6:ds1234@auth.tvhv5yi.mongodb.net/Notifications?retryWrites=true&w=majority&appName=Auth"
  EMAIL_USER: "distributedsystems6@gmail.com"
  EMAIL_PASS: "xsxdjfclfmdsazez"
  TEXTBELT_KEY: "textbelt"
  TWILIO_ACCOUNT_SID: "ACe4ef357dacfcb812f7a8e9c339dd9ef2"
  TWILIO_AUTH_TOKEN: "e332e0f6035b9fa6fea5d97d79d10c41"
  TWILIO_PHONE_NUMBER: "+14014098175"
  PORT: "5004"