apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-container
          image: pastadudde/notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: MONGO_URI
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: EMAIL_PASS
            - name: TEXTBELT_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: TEXTBELT_KEY
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: TWILIO_PHONE_NUMBER
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: PORT