apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF81MVJGWEh3UnJsTUtHcTliTWJUMWRCTFhuR0drcU1ndUZIZWFxT2RnTTZ6YUVrVUdFa3lRU24wSjcyRHRTblNIRVBPSjdFcXlRYk5JTGFWcG1GR05UU1k2djAwOFlIeTk1OEE=
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: QUl6YVN5Q21vTXBFempZTGoyVEgxNDhFTUlkemFIZzBRelVqN2tv
