apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://udulajoker026:CvARzY4spvLIQ75l@cluster0.2imectr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "secret"
  EMAIL_USER: "tdmahindarathne@gmail.com"
  EMAIL_PASS: "cdbribzpyuaqqqsd"
  PORT: "5001"
  GOOGLE_CLIENT_ID: "703814824617-cinrnonku243qlmlmg453crqgtl94ovl.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
