apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-container
          image: pastadudde/food-delivery-order-service:latest
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: order-secrets