# k8s/order-service/order-secrets-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://your_username:your_password@your_cluster.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "your_jwt_secret_here"
  STRIPE_SECRET_KEY: "your_stripe_secret_key_here"
  STRIPE_WEBHOOK_SECRET: "your_stripe_webhook_secret_here"
  EMAIL_USER: "your_email@gmail.com"
  EMAIL_PASS: "your_app_password_here"
  PORT: "5002"