apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://udulajoker026:CvARzY4spvLIQ75l@cluster0.2imectr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "secret"
  STRIPE_SECRET_KEY: "sk_test_51RFXHwRrlMKGq9bMZnBHYawb33nMVND8wcPO7tbr22sIignw7YySyD42Ui8EqGPN9R41Zz6nNPZ4Qp4Vv8XWYZRY00teZMHq0h"
  STRIPE_WEBHOOK_SECRET: "whsec_haPAOmcjdrIPE2FLZSTleoYAlzJD4D2M"
  EMAIL_USER: "madhini00@gmail.com"
  EMAIL_PASS: "qpso aweo pmlk xyow"
  PORT: "5002"
